import { GAMES } from "./games";

export const CONSOLES = [
  {
    id: "n64",
    name: "Nintendo 64",
    description: "64-bit games, iconic 3D titles",
    icon: "🕹️",
    color: "from-purple-900 to-purple-700",
    core: "n64",
    games: GAMES.filter((g) => g.core === "n64"),
    count: GAMES.filter((g) => g.core === "n64").length,
  },
  {
    id: "gba",
    name: "Game Boy Advance",
    description: "Handheld classics but with a functioning screen this time!",
    icon: "🎮",
    color: "from-green-900 to-green-700",
    core: "gba",
    games: GAMES.filter((g) => g.core === "gba"),
    count: GAMES.filter((g) => g.core === "gba").length,
  },
  {
    id: "psx",
    name: "PlayStation",
    description: "32-bit (yes, surprisingly) classics",
    icon: "💿",
    color: "from-blue-900 to-blue-700",
    core: "psx",
    games: GAMES.filter((g) => g.core === "psx"),
    count: GAMES.filter((g) => g.core === "psx").length,
  },
  {
    id: "snes",
    name: "Super Nintendo",
    description: "16-bit classics",
    icon: "🎮",
    color: "from-gray-900 to-gray-700",
    core: "snes",
    games: GAMES.filter((g) => g.core === "snes"),
    count: GAMES.filter((g) => g.core === "snes").length,
  },
  {
    id: "nes",
    name: "Nintendo Entertainment System",
    description: "8-bit, humble beginnings",
    icon: "👾",
    color: "from-red-900 to-red-700",
    core: "nes",
    games: GAMES.filter((g) => g.core === "nes"),
    count: GAMES.filter((g) => g.core === "nes").length,
  },
  {
    id: "nds",
    name: "Nintendo DS",
    description: "! Use the desmume2015 Core for  better performance !",
    icon: "💿",
    color: "from-red-300 to-red-500",
    core: "nds",
    games: GAMES.filter((g) => g.core === "nds"),
    count: GAMES.filter((g) => g.core === "nds").length,
  },
  {
    id: "segaSaturn",
    name: "Sega Saturn",
    description: "Underrated, but Dreamcast is still their magnum opus",
    icon: "🪐",
    color: "from-purple-600 to-purple-300",
    core: "segaSaturn",
    games: GAMES.filter((g) => g.core === "segaSaturn"),
    count: GAMES.filter((g) => g.core === "segaSaturn").length,
  },
  {
    id: "psp",
    name: "Playstation Portable",
    description: "I need to buy a physical psp one day...",
    icon: "💿",
    color: "from-blue-300 to-blue-500",
    core: "psp",
    games: GAMES.filter((g) => g.core === "psp"),
    count: GAMES.filter((g) => g.core === "psp").length,
  },
  {
    id: "segaMD",
    name: "Sega Genesis / MegaDrive",
    description: "sega does what nintendon't and blast processing...",
    icon: "💿",
    color: "from-pink-300 to-pink-500",
    core: "segaMD",
    games: GAMES.filter((g) => g.core === "segaMD"),
    count: GAMES.filter((g) => g.core === "segaMD").length,
  },
].filter((console) => console.count > 0); // exclusively show consoles that have games, will add more later lazy idk
