import { Game } from "@/types/game";

// .zip och 7z filer funkar bra, finns en funktion i emulatorjs extractzip() / extract7z() som drar ut filen.
export const GAMES: Game[] = [
  {
    id: "starfox",
    name: "Star Fox",
    core: "n64",
    url: "https://files.catbox.moe/votlhe.z64",
    description: "",
  },
  {
    id: "doa",
    name: "DoA",
    core: "psx",
    url: "https://files.catbox.moe/f6ooqh.zip",
    description: "",
  },
  {
    id: "harmony-of-dissonance",
    name: "Castlevania Harmony of Dissonance",
    core: "gba",
    url: "https://files.catbox.moe/59tz5j.gba",
    description: "",
  },
  {
    id: "turtles-in-time",
    name: "TMNT: Turtles in Time",
    core: "snes",
    url: "https://files.catbox.moe/hr8y21.sfc",
    description: "",
  },
  {
    id: "battletoads-nes",
    name: "Battletoads",
    core: "nes",
    url: "https://files.catbox.moe/6gj1tb.nes",
    description: "",
  },
  {
    id: "sotn",
    name: "Castlevania: Symphony of the Night",
    core: "psx",
    url: "/api/archive/download/ffta2grim.nds/cstlvnia.7z", // folder organization + infinite file sizes + ejs extracts zips. need indexeddb caching because redownloading 350mb still
    description: "",
  },
  {
    id: "Final Fantasy Tactics Advance",
    name: "Final Fantasy Tactics Advance",
    core: "gba",
    url: "https://files.catbox.moe/mnn04q.gba",
    description: "",
  },
  {
    id: "ffta2",
    name: "Final Fantasy Tactics A2",
    core: "nds",
    url: "/api/archive/download/ffta2grim.nds/ffta2grim.nds",
    description: "",
  },
  {
    id: "gg-dust-strikers",
    name: "Guilty Gear: Dust Strikers",
    core: "nds",
    url: "/api/archive/download/ffta2grim.nds/ggdvststrikrz.zip",
    description: "",
  },
  {
    id: "virton-cybertroopers",
    name: "Virtual On - Cyber Troopers",
    core: "segaSaturn",
    url: "/api/archive/download/ffta2grim.nds/Virtual%20On%20-%20Cyber%20Troopers%20%28USA%29.7z",
    description: "",
  },
  {
    id: "princess-crown",
    name: "Princess Crown",
    core: "segaSaturn",
    url: "/api/archive/download/princess-crown-english-v-0.95-ex/Princess%20Crown%20%28English%20Patched%20v1.0RC3%20EX%29.7z",
    description: "EN fanTL, old Vanillaware game",
  },
  {
    id: "star-ocean",
    name: "Star Ocean",
    core: "snes",
    url: "/api/archive/download/ffta2grim.nds/Star%20Ocean%20%28tr%29.zip",
    description: "fan TL",
  },
  {
    id: "front-mission-iii",
    name: "Front Mission III",
    core: "psx",
    url: "/api/archive/download/ffta2grim.nds/Front%20Mission%203%20%28USA%29.7z",
    description: "",
  },
  {
    id: "ff-tactics-wotl",
    name: "Final Fantasy Tactics: WOTL",
    core: "psp",
    url: "/api/archive/download/ffta2grim.nds/Final%20Fantasy%20Tactics%20The%20War%20of%20the%20Lions%20%28Wolt%20USA%20fast%20fix%20by%20Nexus%29.iso",
    description: "animation fix ver. - better than the 2025 remake btw", // ofc it doesnt work even though it should wow
  },
  {
    id: "disgaea",
    name: "Disgaea: Afternoon of Darkness",
    core: "psp",
    url: "/api/archive/download/ffta2grim.nds/Disgaea%20-%20Afternoon%20of%20Darkness%20%28USA%29.7z",
    description: "fin -> export savefile -> load disc 2 -> import save file",
  },
  {
    id: "chrono-trigger",
    name: "Chrono Trigger",
    core: "snes",
    url: "/api/archive/download/ffta2grim.nds/Chrono%20Trigger%20%28USA%29.zip",
    description: "++++",
  },
  {
    id: "ff-ix",
    name: "Final Fantasy IX (DISC 1)",
    core: "psx",
    url: "/api/archive/download/ffta2grim.nds/Final%20Fantasy%20IX%20%28USA%2C%20Canada%29%20%28Disc%201%29%20%28Rev%201%29.7z",
    description: "fin -> export savefile -> load disc 2 -> import save file",
  },
  {
    id: "ff-viii",
    name: "Final Fantasy VIII (DISC 1)",
    core: "psx",
    url: "/api/archive/download/ffta2grim.nds/Final%20Fantasy%20VIII%20%28USA%29%20%28Disc%201%29.7z",
    description: "fin -> export savefile -> load disc 2 -> import save file",
  },
  {
    id: "vagrant-story",
    name: "Vagrant Story",
    core: "psx",
    url: "/api/archive/download/ffta2grim.nds/Vagrant%20Story%20%28USA%29.7z",
    description: "",
  },
  {
    id: "ff-tactics",
    name: "Final Fantasy Tactics",
    core: "psx",
    url: "/api/archive/download/ffta2grim.nds/Final%20Fantasy%20Tactics%20%28USA%29.7z",
    description: "",
  },
  {
    id: "psiv",
    name: "Phantasy Star IV",
    core: "segaMD",
    url: "/api/archive/download/ffta2grim.nds/Phantasy%20Star%20IV%20%28USA%29.zip",
    description: "",
  },
  {
    id: "dgm-w",
    name: "Digimon World",
    core: "psx",
    url: "/api/archive/download/ffta2grim.nds/Digimon%20World%20%28USA%29.7z",
    description: "",
  },
  {
    id: "fire-emblem",
    name: "Fire Emblen: The Binding Blade",
    core: "gba",
    url: "/api/archive/download/ffta2grim.nds/Fire%20Emblem%20-%20The%20Binding%20Blade%20%28T%29.zip",
    description: "",
  },
  {
    id: "fire-red",
    name: "Pokemon Fire Red",
    core: "gba",
    url: "/api/archive/download/ffta2grim.nds/Pokemon%20-%20FireRed%20Version%20%28USA%2C%20Europe%29%20%28Rev%201%29.zip",
    description: "",
  },
  {
    id: "sapphire",
    name: "Pokemon Sapphire",
    core: "gba",
    url: "/api/archive/download/ffta2grim.nds/Pokemon%20-%20Sapphire%20Version%20%28USA%2C%20Europe%29%20%28Rev%202%29.zip",
    description: "",
  },
  {
    id: "ogre",
    name: "Tactics: Ogre",
    core: "psx",
    url: "/api/archive/download/ffta2grim.nds/Tactics%20Ogre%20%28USA%29.7z",
    description: "",
  },
];
