/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ArcadeRouteImport } from './routes/arcade'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleIdkRouteImport } from './routes/console/idk'
import { Route as ConsoleConsoleIdRouteImport } from './routes/console/$consoleId'

const ArcadeRoute = ArcadeRouteImport.update({
  id: '/arcade',
  path: '/arcade',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIdkRoute = ConsoleIdkRouteImport.update({
  id: '/console/idk',
  path: '/console/idk',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleConsoleIdRoute = ConsoleConsoleIdRouteImport.update({
  id: '/console/$consoleId',
  path: '/console/$consoleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeRoute
  '/console/$consoleId': typeof ConsoleConsoleIdRoute
  '/console/idk': typeof ConsoleIdkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeRoute
  '/console/$consoleId': typeof ConsoleConsoleIdRoute
  '/console/idk': typeof ConsoleIdkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeRoute
  '/console/$consoleId': typeof ConsoleConsoleIdRoute
  '/console/idk': typeof ConsoleIdkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/arcade' | '/console/$consoleId' | '/console/idk'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/arcade' | '/console/$consoleId' | '/console/idk'
  id: '__root__' | '/' | '/arcade' | '/console/$consoleId' | '/console/idk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArcadeRoute: typeof ArcadeRoute
  ConsoleConsoleIdRoute: typeof ConsoleConsoleIdRoute
  ConsoleIdkRoute: typeof ConsoleIdkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/arcade': {
      id: '/arcade'
      path: '/arcade'
      fullPath: '/arcade'
      preLoaderRoute: typeof ArcadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/idk': {
      id: '/console/idk'
      path: '/console/idk'
      fullPath: '/console/idk'
      preLoaderRoute: typeof ConsoleIdkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/$consoleId': {
      id: '/console/$consoleId'
      path: '/console/$consoleId'
      fullPath: '/console/$consoleId'
      preLoaderRoute: typeof ConsoleConsoleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArcadeRoute: ArcadeRoute,
  ConsoleConsoleIdRoute: ConsoleConsoleIdRoute,
  ConsoleIdkRoute: ConsoleIdkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
